#--------------------------------------------------------------------------------
# Values for this workshop - EDIT THIS SECTION.
#--------------------------------------------------------------------------------
workshop_repo   : "https://github.com/COMBINE-Australia/2019-08-20_Data-Extraction-Python-Workshop_Brisbane"
workshop_site   : "http://combine-australia.github.io/2019-08-20_Data-Extraction-Python-Workshop_Brisbane"
#--------------------------------------------------------------------------------
# Standard Software Carpentry settings - should not need to be modified.
#--------------------------------------------------------------------------------
#swc_blog        : "http://software-carpentry.org/feed.xml"
#swc_contact     : "admin@software-carpentry.org"
#swc_files       : "http://files.software-carpentry.org"
#swc_github      : "https://github.com/COMBINE-Australia"
#swc_githubio    : "http://swcarpentry.github.io/"
#swc_installer   : "https://github.com/swcarpentry/windows-installer/releases/download/v0.3/SWCarpentryInstaller.exe"
#swc_site        : "http://combine.org.au"
#swc_twitter     : "http://twitter.com/swcarpentry"
#swc_vm          : "https://docs.google.com/uc?id=0B4Kr6DYkzkQtSTZLQzF4aVB4NDQ&export=download"
#swc_pre_survey  : "https://www.surveymonkey.com/r/swc_pre_workshop_v1?workshop_id="
#swc_post_survey : "https://www.surveymonkey.com/r/swc_post_workshop_v1?workshop_id="
#--------------------------------------------------------------------------------
# Settings for Jekyll - should not need to be modified.
#--------------------------------------------------------------------------------
markdown        : kramdown
kramdown        :
  entity_output : as_input # &mdash; is output as &mdash;
  smart_quotes  : [39, 39, 34, 34] # decimal for left/right single/double quotes
exclude         : [tools]
